### ISSUE TITLE
Issue in javascript Calculator

### ISSUE THREAD

**Issue by HumbleFool830** [dominic754/CalculatorInEveryLanguage#2]
There are some issues in javascript calculator we want to modify the code for that language dominic

**Comment by dominic754** [comment]
Hi, feel free to fork the repository and fix the code that needs to be fixed, I should be able to accept it by tonight.

**Comment by HumbleFool830** [comment]
> and fix the code that

That's ok but It is taken some to organise the code after that you want to give me a pull request chance ok
